### PR TITLE
fixes #646

### LINKED ISSUE #646: Feature Request: Allow HTTP BASIC in URL
I just tried specifing a phpMyAdmin URL like `https://pma:password@froxlor.domain.tld/pma/` at `Settings - Panel Settings - phpMyAdmin URL`. Unfortunately the validator seems not to accept `:` or `@` within the URL and fails with following error:

```
The value for the field "panel_phpmyadmin_url" is not in the expected format.
```

It would be nice to be able to specify a HTTP-BASIC auth URL, as I'd like to hide PMA behind a simple HTTP BASIC Authentication for security-purposes, and also to let users just click on the link without manually entering the HTTP Basic Auth.

### PR DESCRIPTION
**Pull request by pquerner**
change regex by using well tested regex from here:
https://mathiasbynens.be/demo/url-regex

by @diegoperini
https://gist.github.com/dperini/729294

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Using URL http://user:password@froxlor.pma.de for phpMyAdmin.

**Test Configuration**:

* Distribution: debian strech
* Kernel: 4.15.0-47-generic (x86_64)
* Webserver: nginx/1.14.2
* PHP: 7.2.16-1+0~20190307202415.17+stretch~1.gbpa7be82

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by d00p** [comment]
This would also apply to the settings for webmail-url, webftp-url and custom-newsfeed - thanks

**Comment by pquerner** [comment]
What I noticed and didnt realize until now is, that it invalidates private IP space. It shouldnt really matter, tho, I think. If we want this, I would add a workaround to check private IP space first since fixing the regex - for me atm - is an impossible task.

What do you think @d00p  ?

**Comment by d00p** [comment]
Hmm, good question. Reading the source I'd say private IP's were invalid all along :)

**Comment by diegoperini** [comment]
I'm wrongly credited here. @dperini is the person who wrote the regex.

**Pull request merged**
