### PR TITLE
Fix issue #904 Email validation bug

### PR DESCRIPTION
**Pull request by bloodhunterd**
# Description

The if statement cares about that the **validateEmail** function always returns a boolean value.

Fixes # 904

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Debugged the code and tested directly with debug statements.

**Test Configuration**:

* Distribution: Debian
* Webserver: NGINX
* PHP: 7.4

### CODE REVIEW

**Review by d00p — CHANGES_REQUESTED** [review]
Travis fails as you just changed the return type of that function ... it is supposed to return the email address if valid, usages like this occur:

 `$email = \Froxlor\Validate\Validate::validateEmail($_POST['loginemail'], 'email');`

**Comment by d00p** [comment]
refs #904

**Comment by bloodhunterd** [comment]
Ah I see...
So my proposal would be to seek for all of the occurrences of this construct in the code and separeted the validation check from the return value like this:
```
$email = \Froxlor\Validate\Validate::validateEmail($_POST['loginemail'], 'email') ? $_POST['loginemail'] : false;
```
But that would mean that the test also have to be adjusted. Are you fine with this?

**Comment by d00p** [comment]
No, the problem is within the settings-saving, not the validation or its return or usage elesewhere

**Pull request closed without merging**
