### PR TITLE
[WIP] czech.lng.php

### PR DESCRIPTION
**Pull request by rex2630**
I tested it after it got released to public and it doesnt work, is there any file to change for froxlor to support it? And in this PR I'm continuing to work on this lang.

### CODE REVIEW

**Comment by rex2630** [comment]
How to prepare strings for release 0.11? Lot of strings seems to be missing in the dev branch.

**Comment by d00p** [comment]
> How to prepare strings for release 0.11? Lot of strings seems to be missing in the dev branch.

same way as always....just the filenames are a bit different. English (en.lng.php) is the default/base. Everthing in there needs to be/should be translated in the target language-file.

**Comment by d00p** [comment]
Is still still being worked on?

**Comment by d00p** [comment]
no feedback

**Pull request closed without merging**
