### PR TITLE
Run acme.sh upgrade just once when cron starts

### PR DESCRIPTION
**Pull request by patschi**
Only run acme.sh upgrade command once when cronjob starts, and not everytime when there's a certificate going to be renewed.

### CODE REVIEW

**Comment by d00p** [comment]
ah, didn't know it automatically checks for updates everytime...thanks...if only i hadn't just changed a lot of code xD

**Comment by d00p** [comment]
Hm, seems like acme.sh is downloading nad installing regardless of the version...maybe we should checkUpdate only once a day or something....it even does this when there's nothing to renew or similar, meaning every 5 minutes (default)....

**Comment by patschi** [comment]
What the idea of doing the `checkUpgrade()` just before running it the first renewal command in the cronjob AND when there's at least one certificate to issue or renew by Froxlor? This way we don't need an own cronjob or so for that.

`acme.sh` itself is quite small and the download is quite fast. So we ensure that the client is always up-to-date prior renewing, in case of any fixes or improvements or so.

**Comment by d00p** [comment]
just commited something xD but yes, that idea is better :)

**Pull request merged**
