### PR TITLE
Bug #1533

### PR DESCRIPTION
**Pull request by RipClaw2971**
"Require all granted" wurde nicht gesetzt wenn man mod_proxy_fcgi verwendet

### CODE REVIEW

**Comment by d00p** [comment]
Explain/show why this is necessary please. I dont have problems with it for months...

**Comment by RipClaw2971** [comment]
The default configuration in /etc/apache2/apache2.conf in Debian Jessie is this:

<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

There are two options to allow access to the websites. The first one is a global solution:

<Directory /var/customers/webs>
        Require all granted
</Directory>

The second is a "Require all granted" per virtual host.

**Comment by d00p** [comment]
As said, i have this setup for months, no problem..don't see why this is necessary

**Comment by RipClaw2971** [comment]
If you don't set a "Require all granted" for the directory the only thing you see is "Forbidden".
In the apache2.conf there are two other blocks to whitelist /var/www and /usr/share

```

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

```

I've got the problem yesterday on my new server and tracked the "Forbidden" down to the apache2.conf. The only working solution was to set a "Require all granted" to every virtual host to the document root.

**Comment by d00p** [comment]
Well, additional "require"s are no harm - maybe it's just works for me on gentoo out of the box

**Pull request merged**
