### PR TITLE
Rename dovecot config file generated be renew hook to ensure it gets after default froxlor config file

### PR DESCRIPTION
**Pull request by sro0**
# Description

Currently generated file names by Froxlor for Dovecot using Debian Bookworm:
- /etc/dovecot/conf.d/99-froxlor.conf (from service config)
- /etc/dovecot/conf.d/99-froxlor-ssl.conf (from renew hook)

Dovecot includes all `conf.d/*.conf` files like this [dovecot.conf](https://github.com/dovecot/core/blob/35cba09cf91d79402f44ccdff8246c19caa2622e/doc/example-config/dovecot.conf#L92):
> The filenames are first sorted by their ASCII value and parsed in that order.

`.` == 0x2e
`-` == 0x2d

Thats why `99-froxlor-ssl.conf` gets parsed before `99-froxlor.conf` and the TLS values from renew hook might get overwritten.

# Solution
Choose filename for file generated by rename hook that gets parsed after default Froxlor config file.

# Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

**Test Configuration**:
* Distribution: Gentoo
* Dovecot: 2.3.20

# Checklist:
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by d00p** [comment]
Thanks for the contribution, although as stated in the code, it's not even final this way, as this might to be a setting (at least for the path). Just to be totally sure - would using `999-froxlor...` ensure it's read in last?

**Comment by sro0** [comment]
Yes you are right, using `999-froxlor...` works. Just verified this.
Just depends if we want to break the 2 digit style that is used until now.

**Comment by d00p** [comment]
We could also use `99-zzz-froxlor` but I think that's looks crappy :p

**Comment by sro0** [comment]
Yeah whatever ^^. I just tripped over this while testing and this PR is a quick (and dirty) workaround.
As long as it is fixed in the final release (maybe with a setting for path), feel free to drop this PR.

**Comment by d00p** [comment]
na i'll take it for now as it fixes the correct include order, thanks again :)

**Pull request merged**
