### PR TITLE
ignore package-lock.json

### PR DESCRIPTION
**Pull request by rubo77**
This file should not be within the git repository, since it is automatically edited, when you run the install instructions:

```
composer install --no-dev
npm install
npm run build
```

### CODE REVIEW

**Comment by d00p** [comment]
same as composer.lock, it represents the package versions installed/tested for a release and thus used for building the release packages (instead of package.json).

Also relevant for developers: It allows future devs to install the same dependencies in the project.

**Comment by rubo77** [comment]
Ah ok. So would you like to see the changes to the file, that were automatically made in my repository, and update the file then?

**Comment by d00p** [comment]
You obviously don't understand and rather discuss meaningless on GitHub then talk to us on discord.

**Comment by discordier** [comment]
For the record, install as follows:
```
composer install --no-dev
npm ci
npm run build
```
See https://docs.npmjs.com/cli/v9/commands/npm-ci

That way you get the dependencies as intended.

`npm install` is for developers that want to get current dependencies.

**Pull request closed without merging**
