### PR TITLE
Make writing AccessLog and ErrorLog optional

### PR DESCRIPTION
**Pull request by ServiusHack**
In GDPR's spirit of data minimisation it should be possible to not write any log files. With this change each domain gets the option to disable the access and error log of Apache.

### CODE REVIEW

**Comment by d00p** [comment]
Nice PR, what about nginx and lighttpd crons?

**Comment by ServiusHack** [comment]
Good question. Didn't think of the others as I'm only using Apache.

Since there we no comments on the code I took the liberty to amend my previous commit. Hope that's ok. Lighttpd and Nginx now also consider the settings. I tested it a bit but not each combination of the settings.

**Comment by d00p** [comment]
not compatible with current master-branch, do you want to adjust the changes?

**Comment by ServiusHack** [comment]
I'll look into it this weekend. Hopefully the pull request won't stay open for another two months then, until there are conflicts again.

**Comment by d00p** [comment]
it stayed open so long because I was about finished with 0.9.x and already putting work in 0.10.0 which is now master branch after the release of 0.9.40

**Pull request merged**
