### PR TITLE
Changes in the config templates

### PR DESCRIPTION
**Pull request by ianklemm**
Hello, 

I updated 2 things in the jessie config template:

- enabled plaintext auth because with no TLS enabled, you can´t login to the maildeamon
- disabled RLimitChroot because it brings some problems with it in shared hosting

### CODE REVIEW

**Comment by d00p** [comment]
Please remove the rar file ;)

**Comment by ianklemm** [comment]
Done

**Comment by d00p** [comment]
And why do the changes only for Jessie?

**Comment by ianklemm** [comment]
I will change it for the other distributions in the next minutes..

**Comment by ianklemm** [comment]
In Wheezy is the mail config correct. It also uses an older version of proFTPd, so you don´t have to disable RLimitChroot.
In other distributions, I have fixed the error, if it was necessary.

**Pull request merged**
