### PR TITLE
Improve composer.json syntax

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
# Description

This change improves the syntax in composer.json.

1. `php` was listed twice (in `require` and `require-dev`).
2. `>=` syntax should be avoided to account for breaking changes in major PHP versions. `^` allows minor updates, but not major

(3. I would like to see the minimum version raised to PHP 7.4, as 7.1 and 7.2 are no longer updated and should not be supported in my opinion. **Can I also implement this in this PR?**)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

--

**Test Configuration**:

--

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by d00p** [comment]
> (3. I would like to see the minimum version raised to PHP 7.4, as 7.1 and 7.2 are no longer updated and should not be supported in my opinion. Can I also implement this in this PR?)

This is discussed very often and I'm totally with you on this but from my experience, there are too many users who are still on older distributions and only stick with the default php (which e.g. for debian buster is 7.3).
As long as the source does not really require a higher php version, there is no reason to raise the requirement (development point of view).

**Comment by MrKrisKrisu** [comment]
Okay! That's why i've asked before just doing it in the PR. :)

Do you agree with the rest of the change?

**Comment by d00p** [comment]
basically yes, but from a brief overview of the lock file, can we be sure that we do not break compatibility with php-7.1? (not dev-environment of course)

**Comment by MrKrisKrisu** [comment]
The only php version changes in the lock file are from:

- `phpspec/prophecy` up to `^7.2` 
    - only used in require-dev

- `psr/container` from `>=7.2` to `>=7.4` 
    - used by `symfony/dependency-injection`
    - used by `pdepend/pdepend`
    - used by `phpmd/phpmd`
    - only used in require-dev

So I did not find any version changes in the lockfile. Only dev-reqs has been changed to a minimum of PHP 7.4.

**Pull request merged**
