### PR TITLE
fix group by clause to be be compliant with mysql 5.7

### PR DESCRIPTION
**Pull request by FliegenKLATSCH**
In mysql 5.7 only_full_group_by is enabled by default.

### CODE REVIEW

**Comment by d00p** [comment]
Are you going to find even more "fixes" or is this mergable (and tested?)

**Comment by FliegenKLATSCH** [comment]
I don't know, if there are more of this issue.. I don't see any, but I'm not a "power-user"..
So you can merge it, it's tested.. If I find another one, I'll create another pull-request.

**Comment by FliegenKLATSCH** [comment]
Whats the status now? Should I change something?

**Comment by nachtgeist** [comment]
* please clean up the history of your pull request (i.e. fix-up ad6b39a and 779e41e into a single commit)
* you changed froxlor.sql - this file is used for a clean installation only. What's missing is code for migrating existing installations. Have a look at install/updates/froxlor/0.9/update_0.9.inc.php

**Pull request closed without merging**
