### PR TITLE
Added entry for 'ftp' to the DNS

### PR DESCRIPTION
**Pull request by princeofnaxos**
# Description

An entry for 'ftp' fails in the DNS zone file. 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran the master cronjob.

**Test Configuration**:

* Distribution: Debian 9
* Webserver: Apache 2.4
* PHP: PHP-FPM 7.3

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by d00p** [comment]
don't see why this should be necessary

**Comment by d00p** [comment]
at least make it an option as we do it for mail-entries (setting system.dns_createmailentry)

**Comment by princeofnaxos** [comment]
Because ftp.[domain] doesn't exist, when not a wildcard domain? 
Customers that use FTP are used to that subdomain.

**Comment by d00p** [comment]
Then please make it an option.

**Comment by discordier** [comment]
And please default it to off!

I do not want my zone files cluttered with hosts that are not needed (my FTP is running on one IP whereas the HTTP is running on another) so this would definitely cause confusion for many customers why there is a ftp defined but not reachable.

**Pull request closed without merging**
