### PR TITLE
Removed query parameter s, used cookies instead

### PR DESCRIPTION
**Pull request by shyim**
I guess everyone hates the sessionid in the query. Best example is go back to a specifc site with changing the request uri, if i forget the session i will be logged out or bookmarking specifc sites its impossible :(

### CODE REVIEW

**Comment by d00p** [comment]
Already done for 2.0, i dont really want such huge changes in 0.9.x - other thoughts @Dessa @nachtgeist @BNoiZe ?

**Comment by nachtgeist** [comment]
what d00p said...

**Comment by shyim** [comment]
And why is the 2.0 branch not available on github.................

**Comment by d00p** [comment]
Because of various reasons. It will be when it reaches the wanted state.

**Pull request closed without merging**
