### PR TITLE
Prevent duplicates in ipsandports table

### PR DESCRIPTION
**Pull request by negrusti**
Hi,
I manipulate Froxlor tables from my own scripts and think that this constraint will be right in this table.

### CODE REVIEW

**Comment by negrusti** [comment]
Sorry for noob question - is my 2nd commit visible now in pull request? Also unsure about Froxlor version check

**Comment by nachtgeist** [comment]
> is my 2nd commit visible now in pull request?

yes

> Also unsure about Froxlor version check

Since DB versioning was introduced you need to check for the database version instead... just add your migration code at the very end of that file and use `isDatabaseVersion('YYYYMMDD#')` with the value used in `updateToDbVersion()` in the previous migration.

And then there's another issue: this code will fail if there already are duplicate entries.
@d00p: any idea how to handle this in a sensible and useful way?

**Comment by negrusti** [comment]
In my experience when duplicates are accidentally created, Froxlor generates unworkable vhost configurations and Apache does not start with it.

**Comment by nachtgeist** [comment]
ok good enough for me

**Comment by d00p** [comment]
1) froxlor does check for duplicates when adding a new IP/port, see https://github.com/Froxlor/Froxlor/blob/master/admin_ipsandports.php#L216 and following
So, i'm unsure where you get these...

2) totally misplaced update queries, as  @nachtgeist said, add your migration/update code at the end of the update-file and just increase database-version

**Comment by negrusti** [comment]
1) All my fault
2) Moved update queries to the end of the update file with DB version increase, please check

**Comment by d00p** [comment]
Sorry, forgot to mention, please also set $dbversion in lib/version.inc.php :)

**Comment by negrusti** [comment]
Perhaps the code starting here:
https://github.com/Froxlor/Froxlor/blob/master/admin_ipsandports.php#L216
can be simplified now, with INSERT converted to REPLACE on line 226?

**Comment by d00p** [comment]
@negrusti i prefer the way it is with output of a message: hey, this ip/port already exists. and not just "overwriting" - you never know if it was intended or by mistake

**Comment by d00p** [comment]
Froxlor already checks for duplicates and outputs a corresponding error-message. Just adding an UNIQUE-KEY does not change anything about this

**Comment by negrusti** [comment]
The problem is - at the moment Froxlor is poorly suited for automation. Why would you reject this change? Does it have a potential to break anything?

**Comment by d00p** [comment]
Ah NOW someone answers...i should close PR's earlier so people react

**Comment by negrusti** [comment]
I am sorry - I guess I missed some message earlier - I assumed it was already merged

**Comment by d00p** [comment]
And no, it does not break anything but also does not improve anything really...so it's quit unnecessary, but hey, here you go, have fun :)

**Comment by negrusti** [comment]
thanks! :)

**Pull request merged**
