### PR TITLE
Add possibility to have external database server for customers database

### PR DESCRIPTION
**Pull request by ffrewer**
Fixes Bug #1438: Second External database server for customers database
not anymore possible

### CODE REVIEW

**Comment by d00p** [comment]
No feedback for 5 months....anyone tested this?

**Comment by valentinul** [comment]
Not working unfortunately ...

The following error is thrown when a database is created...

A database error occured

SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'root'@'192.120.203.222' to database 'testsql1'
#0 /var/www/froxlor-dev/lib/classes/database/class.Database.php(77): PDOStatement->execute(Array)
#1 /var/www/froxlor-dev/lib/classes/database/manager/class.DbManagerMySQL.php(74): Database::pexecute(Object(PDOStatement), Array)
#2 /var/www/froxlor-dev/lib/classes/database/class.DbManager.php(101): DbManagerMySQL->grantPrivilegesTo('testsql1', 'testPasswd', '127.0.0.1')
#3 /var/www/froxlor-dev/customer_mysql.php(174): DbManager->createDatabase('test', 'testPasswd', '0', '1')
#4 {main}

The database is nevertheless created on the remove box:

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| froxlor            |
| mysql              |
| performance_schema |
| testsql1           |
+--------------------+
5 rows in set (0.00 sec)

**Comment by valentinul** [comment]
Ok, I fixed the rights issue...it was related to the root user missing the grant_priv.
Fixed by -> UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root';

Now everything works perfectly!

**Comment by d00p** [comment]
outdated

**Pull request closed without merging**
