### PR TITLE
[WIP] Update of the Czech lang

### PR DESCRIPTION
**Pull request by rex2630**

### CODE REVIEW

**Comment by d00p** [comment]
Is this still being worked on?

**Comment by Neustradamus** [comment]
@rex2630: Have you seen the @d00p comment?

**Comment by rex2630** [comment]
Yes, i have read the message. This PR is being worked on really rarely, i have it still opened in case i would want to continue, but if u find it disturbing here then u can close it i guess,

**Comment by Neustradamus** [comment]
@rex2630: Why have you closed?

**Comment by rex2630** [comment]
I'm making more completed version and that branch was way too behing anyways

**Pull request closed without merging**
