### PR TITLE
Update cron_letsencrypt.php

### PR DESCRIPTION
**Pull request by Amaridian**
When using data from previous cert, check if it was issued by let's encrypt to prevent invalid data.

### CODE REVIEW

**Comment by d00p** [comment]
Tested?

**Comment by nachtgeist** [comment]
What by your definition is invalid data?

**Comment by Amaridian** [comment]
it is tested (and solved problems) on two of my servers. 

In my case, i had a StartSSL wildcard cert installed and activated letsencrypt for that domain. The froxlor cronjob took this wildcard-entry from my old cert to request a new cert from letsencrypt. This resulted in an error message from letsencrypt (no wildcard-certs allowed). 

The old code didnt check an existing cert for its issuer.... with my changes it does exactly that. Old cert data is only referenced when the issuer is letsencrypt.

**Comment by nachtgeist** [comment]
While it makes sense what you're trying to accomplish, the textual issuer verification IMO is pointless. 

So unless you check against the LE CA certificates I vote against this.

**Comment by Amaridian** [comment]
Well, generally, the whole import of any data from "old" certificates does not make a lot of sense. The cronjob should check for the current settings for the current domain, more or less calculate the needed subdomains and then check if all this data coresponds with the data from the last known cert. Based on this it should either renew the current cert or get a new one.

**Comment by nachtgeist** [comment]
With PR #353 merged, this is no longer relevant. CSRs now get re-created every time a certificate is to be requested from LE, disregarding any pre-existing CSRs.

**Comment by d00p** [comment]
Obsolete as of https://github.com/Froxlor/Froxlor/pull/353

**Pull request closed without merging**
