### PR TITLE
Add the posibility to create new mailboxes with first- and lastname

### PR DESCRIPTION
**Pull request by virusbrain**
This patch provides the positbility to create a new mailbox with a firstname and a
lastname. This is very useful if you want to connect these mailboxes with a groupware.
For the case that the feature is not wanted: There was added a setting for this feature.
Default status of this feature is disabled.

### CODE REVIEW

**Comment by d00p** [comment]
If wanted/needed why is the name not shown on the mail-address overview then? You can see whether a name was stored for an account / address only if you edit the address

**Comment by virusbrain** [comment]
Because the name can only be shown if the mail-address is a real mailbox - not only a forwarding address. If the name should be shown I think it would be better to spilt the email part into two seperate pages: One Mailbox overview and one forward-address overview.

**Comment by d00p** [comment]
Well, you know you can use if-statements in templates? I dont hink this makes any sense if you do not display the stored name anywhere...if theres no reaction here this PR will be closed

**Comment by d00p** [comment]
no reaction for over a year, closed as said

**Pull request closed without merging**
